### ISSUE TITLE
Fix token authorization for TodoList

### ISSUE THREAD

**Issue by RezaBG** [RezaBG/TUDU_FE#2]
The frontend app fails to use the correct JWT token when fetching the todos, causing 401 Unauthorised errors.

<img width="1750" alt="image" src="https://github.com/user-attachments/assets/a5e1a5ee-f387-4144-8997-0b16acb2b5bc">

Jira ticket: https://boir.atlassian.net/browse/KAN-85

**Comment by gnerkus** [comment]
I wouldn't call this a bug.

The reason this happens is that the token you saved to `localStorage` expires and needs to be renewed. Usually, this is done with a login but we don't have this yet so I'll suggest a couple of ways you can work around this:

a. Disable the auth requirement for the API endpoints when testing the frontend
b. Before testing the frontend, generate a new token and save this in `localStorage`

**Comment by gnerkus** [comment]
You should also ensure the token is actually being passed along in the `Authorization` header.

**Comment by gnerkus** [comment]
I think we can close this.
